const ROLES = require("./roles");

const rolePermissions = {
  [ROLES.SUPER_ADMIN]: [
    "MANAGE_ALL_SHOPS",
    "CREATE_ADMIN",
    "VIEW_ALL_DATA",
    "MANAGE_PRODUCTS",
    "MANAGE_STOCK",
    "MANAGE_CUSTOMERS",
    "MANAGE_DISTRIBUTORS",
    "MANAGE_USERS",
    "MANAGE_SETTINGS",
    "APPROVE_RECONCILIATION",
  ],

  [ROLES.ADMIN]: [
    "CREATE_MANAGER",
    "CREATE_STAFF",
    "MANAGE_PRODUCTS",
    "MANAGE_STOCK",
    "MANAGE_CUSTOMERS",
    "MANAGE_DISTRIBUTORS",
    "VIEW_REPORTS",
    "MANAGE_SETTINGS",
    "APPROVE_RECONCILIATION",
  ],

  [ROLES.MANAGER]: [
    "MANAGE_PRODUCTS",
    "MANAGE_STOCK",
    "MANAGE_CUSTOMERS",
    "MANAGE_DISTRIBUTORS",
    "VIEW_REPORTS",
    "CREATE_PURCHASE",
  ],

  [ROLES.STAFF]: [
    "CREATE_SALE",
    "VIEW_REPORTS",
  ],
};

module.exports = rolePermissions;
