const ROLES = require("./roles");

const roleFeaturePolicy = {
  [ROLES.STAFF]: [
    "dashboard.basic",
    "sales.list",
    "sales.create",
    "sales.payment",
    "staff.daily_work",
    "staff.payments",
    "expenses.daily",
    "people.customers",
  ],
  [ROLES.MANAGER]: [
    "dashboard.basic",
    "sales.list",
    "sales.create",
    "sales.return",
    "sales.payment",
    "sales.pos",
    "sales.orders",
    "inventory.products",
    "inventory.product_details",
    "inventory.stocks",
    "factory.product_master",
    "factory.verification",
    "factory.raw_material_master",
    "factory.raw_material_purchase",
    "factory.report",
    "factory.push_to_shop",
    "staff.master",
    "staff.daily_work",
    "staff.payments",
    "staff.summary",
    "expenses.daily",
    "expenses.report",
    "people.customers",
    "settings.profile",
  ],
  [ROLES.ADMIN]: [
    "dashboard.basic",
    "dashboard.financial",
    "sales.list",
    "sales.create",
    "sales.return",
    "sales.payment",
    "sales.reports",
    "sales.profit",
    "sales.pos",
    "sales.orders",
    "inventory.products",
    "inventory.product_details",
    "inventory.stocks",
    "inventory.purchase",
    "factory.product_master",
    "factory.verification",
    "factory.raw_material_master",
    "factory.raw_material_purchase",
    "factory.report",
    "factory.push_to_shop",
    "staff.master",
    "staff.daily_work",
    "staff.payments",
    "staff.summary",
    "expenses.daily",
    "expenses.report",
    "people.customers",
    "people.distributors",
    "people.users",
    "settings.profile",
    "settings.shop",
    "settings.permissions",
    "settings.system",
  ],
  [ROLES.SUPER_ADMIN]: ["*"],
};

module.exports = roleFeaturePolicy;
